#!/usr/bin/env bash
set -euo pipefail

### Variables à ajuster ###
K3S_VERSION="v1.33.1+k3s1"
KS_VERSION="v3.4.1"
GIT_REPO="https://github.com/charlesvdd/kubesphere.git"
GIT_BRANCH="master"  # la branche par défaut est master
STORAGE_CLASS=""  # ou ton StorageClass
SWAP_SIZE_GB=4
WORKDIR="$HOME/kubesphere"
###############################################################################

# Affiche un titre
function title() {
  echo -e "\n===== $1 ====="
}

# 0️⃣ Pré-vérifications
function pre_checks() {
  title "VÉRIFICATIONS PRÉALABLES"
  echo -n "→ OS: " && lsb_release -ds
  MEM_GB=$(free -g | awk '/^Mem:/ {print $2}')
  echo "→ RAM: ${MEM_GB} Go"
  if (( MEM_GB < 8 )); then
    echo "⚠️  Moins de 8 Go de RAM, performance réduite."
  fi
  if swapon --show | grep -q '/swapfile'; then
    echo "→ Swap: ok"
  else
    echo "⚠️  Pas de swap. Le script va créer ${SWAP_SIZE_GB}G de swap."
  fi
}

# 1️⃣ Déploiement complet
function deploy() {
  title "DÉPLOIEMENT"

  # Clone ou pull
  if [ ! -d "$WORKDIR/.git" ]; then
    echo "→ Clonage de $GIT_REPO (branche $GIT_BRANCH)"
    git clone --branch "$GIT_BRANCH" "$GIT_REPO" "$WORKDIR"
  else
    echo "→ Mise à jour (branche $GIT_BRANCH)"
    cd "$WORKDIR"
    git fetch origin "$GIT_BRANCH"
    git reset --hard "origin/$GIT_BRANCH"
  fi
  cd "$WORKDIR"

  # Mise à jour OS et dépendances
  echo "→ Mise à jour apt + dépendances"
  sudo apt update && sudo apt upgrade -y
  sudo apt install -y curl apt-transport-https vim git ca-certificates lsb-release

  # Swap
  if ! swapon --show | grep -q '/swapfile'; then
    echo "→ Création swap ${SWAP_SIZE_GB}G"
    sudo fallocate -l ${SWAP_SIZE_GB}G /swapfile
    sudo chmod 600 /swapfile
    sudo mkswap /swapfile
    sudo swapon /swapfile
    echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab
  fi

  # containerd
  echo "→ Installation containerd"
  sudo apt install -y containerd
  sudo mkdir -p /etc/containerd
  sudo containerd config default | sudo tee /etc/containerd/config.toml >/dev/null
  sudo systemctl restart containerd
  sudo systemctl enable containerd

  # k3s
  echo "→ Installation k3s ${K3S_VERSION}"
  curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION="${K3S_VERSION}" sh -s - \
    --disable traefik \
    --kubelet-arg="eviction-hard=imagefs.available<15%,nodefs.available<15%>"

  # kubectl config
  echo "→ Configuration kubectl"
  mkdir -p $HOME/.kube
  sudo cp /etc/rancher/k3s/k3s.yaml $HOME/.kube/config
  sudo chown $(id -u):$(id -g) $HOME/.kube/config
  export KUBECONFIG=$HOME/.kube/config

  # Manifest KubeSphere
  echo "→ Préparation manifest KubeSphere"
  VPS_IP=$(hostname -I | awk '{print $1}')
  echo "   IP détectée: $VPS_IP"
  # Récupère ton manifest dans le repo master
  curl -fsSL "https://raw.githubusercontent.com/charlesvdd/kubesphere/${GIT_BRANCH}/cluster-configuration.yaml" -o cluster-configuration.yaml

  # Patch IP et StorageClass
  sed -i -E "
    s#(endpointIps:) .*#\1 $VPS_IP#;
    s#(storageClass:) .*#\1 \"${STORAGE_CLASS}\"#g
  " cluster-configuration.yaml

  # Config Git local pour commit
  git config user.email "autodeploy@kubesphere.local"
  git config user.name "KubeSphere AutoDeploy Bot"

  # Commit & push si modifié
  if git status --porcelain cluster-configuration.yaml | grep -q .; then
    title "COMMIT & PUSH"
    git add cluster-configuration.yaml
    git commit -m "Update KubeSphere config with IP $VPS_IP"
    git push origin "$GIT_BRANCH"
  fi

  # Déploiement KubeSphere
  echo "→ Déploiement KubeSphere"
  kubectl apply -f https://github.com/kubesphere/ks-installer/releases/download/${KS_VERSION}/kubesphere-installer.yaml
  kubectl apply -f cluster-configuration.yaml
}

# 2️⃣ Auto-évaluation
function evaluation() {
  title "AUTO-ÉVALUATION"
  echo "Attente pods KubeSphere (max 15 mn)"
  end=$((SECONDS + 900))
  while true; do
    PENDING=$(kubectl get pods -n kubesphere-system --no-headers | grep -E 'ContainerCreating|Pending|CrashLoopBackOff' || true)
    if [ -z "$PENDING" ]; then break; fi
    if (( SECONDS > end )); then
      echo "⚠️ Certains pods n'ont pas démarré"
      kubectl get pods -n kubesphere-system
      exit 1
    fi
    sleep 10
  done

  echo "→ Tous les pods sont Running ✅"
  kubectl get pods -n kubesphere-system -o wide

  echo "→ Vérification nodes"
  kubectl get nodes

  echo "→ Test UI"
  HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://$VPS_IP:30880)
  if [ "$HTTP_CODE" = "200" ]; then
    echo "UI accessible sur http://$VPS_IP:30880 ✅"
  else
    echo "⚠️ UI non accessible (HTTP $HTTP_CODE)"
  fi

  echo -e "\n🎉 DÉPLOIEMENT TERMINÉ !"
}

# MAIN
echo
pre_checks
deploy
evaluation
